Update OpenWrt-Packages 2023.06.17-17:55

diff --git a/kenzok/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic b/kenzok/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
--- a/kenzok/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
+++ b/kenzok/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
@@ -13,7 +13,7 @@ UNM_DIR="/usr/share/$NAME"
 RUN_DIR="/var/run/$NAME"
 
 IPT_N="iptables -t nat"
-IPT_INPUT_RULE="unblockneteasemusic_input_rule"
+IPT_INPUT_RULE="unm_input_rule"
 
 is_enabled() {
 	local enabled
@@ -76,12 +76,13 @@ start_service() {
 	local update_time
 	config_get update_time "config" "update_time" "3"
 	sed -i "/$NAME/d" /etc/crontabs/root
-	is_enabled "config" "auto_update" && echo "0 ${update_time} * * * $UNM_DIR/update.sh update_core" >> "/etc/crontabs/root"
+	echo -e "30 2 * * * /etc/init.d/unblockneteasemusic" >> "/etc/crontabs/root"
+	! is_enabled "config" "auto_update" || echo -e "0 ${update_time} * * * $UNM_DIR/update.sh update_core" >> "/etc/crontabs/root"
 	/etc/init.d/cron restart
 
 	mkdir -p "$RUN_DIR"
-	[ ! -s "$UNM_DIR/core/app.js" ] && { rm -f "$UNM_DIR/local_ver"; sh "$UNM_DIR/update.sh" "update_core_non_restart"; }
-	[ ! -s "$UNM_DIR/core/app.js" ] && { echo "Core Not Found, please download it before starting." >> "$RUN_DIR/run.log"; return 1; }
+	[ -s "$UNM_DIR/core/app.js" ] || { rm -f "$UNM_DIR/local_ver"; sh "$UNM_DIR/update.sh" "update_core_non_restart"; }
+	[ -s "$UNM_DIR/core/app.js" ] || { echo "Core Not Found, please download it before starting." >> "$RUN_DIR/run.log"; return 1; }
 
 	procd_open_instance "$NAME"
 	procd_set_param command node "$UNM_DIR/core/app.js"
@@ -95,10 +96,10 @@ start_service() {
 	append_param "-p" "${http_port}":"${https_port}"
 
 	if is_enabled "config" "pub_access"; then
-		iptables -N "$IPT_RULE_NAME"
-		iptables -t filter -I INPUT -j "$IPT_RULE_NAME"
-		iptables -t filter -A "$IPT_RULE_NAME" -p tcp --dport "${http_port}" -j ACCEPT
-		iptables -t filter -A "$IPT_RULE_NAME" -p tcp --dport "${https_port}" -j ACCEPT
+		iptables -N "$IPT_INPUT_RULE"
+		iptables -t filter -I INPUT -j "$IPT_INPUT_RULE"
+		iptables -t filter -A "$IPT_INPUT_RULE" -p tcp --dport "${http_port}" -j ACCEPT
+		iptables -t filter -A "$IPT_INPUT_RULE" -p tcp --dport "${https_port}" -j ACCEPT
 
 		echo "/etc/init.d/$NAME restart" > "$RUN_DIR/fw3.include"
 	fi
@@ -124,6 +125,7 @@ start_service() {
 	append_param_env "config" "youtube_key" "YOUTUBE_KEY"
 	append_param_env "config" "self_issue_cert_crt" "SIGN_CERT" "$UNM_DIR/core/server.crt"
 	append_param_env "config" "self_issue_cert_key" "SIGN_KEY" "$UNM_DIR/core/server.key"
+	append_param_env "config" "local_vip" "ENABLE_LOCAL_VIP"
 
 	append_param_boolenv "config" "follow_source_order" "FOLLOW_SOURCE_ORDER"
 	append_param_boolenv "config" "search_album" "SEARCH_ALBUM"
@@ -131,7 +133,6 @@ start_service() {
 	append_param_boolenv "config" "select_max_br" "SELECT_MAX_BR"
 	append_param_boolenv "config" "disable_upgrade_check" "DISABLE_UPGRADE_CHECK"
 	append_param_boolenv "config" "block_ads" "BLOCK_ADS"
-	append_param_boolenv "config" "local_vip" "ENABLE_LOCAL_VIP"
 	case "$(config_get "config" "replace_music_source")" in
 		"lower_than_192kbps") procd_append_param env MIN_BR="192000" ;;
 		"lower_than_320kbps") procd_append_param env MIN_BR="320000" ;;
@@ -164,8 +165,8 @@ start_service() {
 		ipset create "neteasemusic" hash:ip
 		config_foreach append_filter_client "acl_rule"
 
-		local netease_music_ips="$(uclient-fetch -qO- "http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.data.*.ip.*')"
-		local netease_music_ips2="$(uclient-fetch -qO- "https://music.httpdns.c.163.com/d" --post-data="music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.dns.*["ips"].*')"
+		local netease_music_ips="$(wget -qO- "http://httpdns.n.netease.com/httpdns/v2/d?domain=music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.data.*.ip.*')"
+		local netease_music_ips2="$(wget -qO- "https://music.httpdns.c.163.com/d" --post-data="music.163.com,interface.music.163.com,interface3.music.163.com,apm.music.163.com,apm3.music.163.com,clientlog.music.163.com,clientlog3.music.163.com" |jsonfilter -e '@.dns.*["ips"].*')"
 		echo -e "${netease_music_ips}\n${netease_music_ips2}" | sort -u | awk '{print "ipset add neteasemusic "$1}' | sh
 
 		$IPT_N -N "netease_cloud_music"
@@ -212,9 +213,9 @@ stop_service() {
 	/etc/init.d/cron restart
 
 	local settable
-	iptables -t filter -D INPUT -j "$IPT_RULE_NAME" 2>"/dev/null"
-	iptables -F "$IPT_RULE_NAME" 2>"/dev/null"
-	iptables -X "$IPT_RULE_NAME" 2>"/dev/null"
+	iptables -t filter -D INPUT -j "$IPT_INPUT_RULE" 2>"/dev/null"
+	iptables -F "$IPT_INPUT_RULE" 2>"/dev/null"
+	iptables -X "$IPT_INPUT_RULE" 2>"/dev/null"
 
 	$IPT_N -D "PREROUTING" -p "tcp" -m set --match-set "neteasemusic" "dst" -j "netease_cloud_music" 2>"/dev/null"
 	$IPT_N -F "netease_cloud_music" 2>"/dev/null"
